import { Instrument } from "./types";

export const DB: Record<string, Instrument[]> = {
  index: [
    { ticker: 'ES', name: 'S&P 500 E-mini', cat: 'Index Futures', type: 'futures', dpp: 50, tick: 0.25, dpt: 12.50, dec: 2 },
    { ticker: 'MES', name: 'S&P 500 Micro', cat: 'Index Futures', type: 'futures', dpp: 5, tick: 0.25, dpt: 1.25, dec: 2 },
    { ticker: 'NQ', name: 'NASDAQ-100 E-mini', cat: 'Index Futures', type: 'futures', dpp: 20, tick: 0.25, dpt: 5.00, dec: 2 },
    { ticker: 'MNQ', name: 'NASDAQ-100 Micro', cat: 'Index Futures', type: 'futures', dpp: 2, tick: 0.25, dpt: 0.50, dec: 2 },
    { ticker: 'YM', name: 'Dow Jones E-mini', cat: 'Index Futures', type: 'futures', dpp: 5, tick: 1.0, dpt: 5.00, dec: 0 },
    { ticker: 'MYM', name: 'Dow Jones Micro', cat: 'Index Futures', type: 'futures', dpp: 0.5, tick: 1.0, dpt: 0.50, dec: 0 },
    { ticker: 'RTY', name: 'Russell 2000 E-mini', cat: 'Index Futures', type: 'futures', dpp: 50, tick: 0.10, dpt: 5.00, dec: 2 },
    { ticker: 'M2K', name: 'Russell 2000 Micro', cat: 'Index Futures', type: 'futures', dpp: 5, tick: 0.10, dpt: 0.50, dec: 2 },
    { ticker: 'FTSE', name: 'FTSE 100 Index', cat: 'Index Futures', type: 'futures', dpp: 10, tick: 0.5, dpt: 5.00, dec: 1 },
    { ticker: 'DAX', name: 'DAX 40 Index', cat: 'Index Futures', type: 'futures', dpp: 25, tick: 0.5, dpt: 12.50, dec: 1 },
    { ticker: 'NK225', name: 'Nikkei 225', cat: 'Index Futures', type: 'futures', dpp: 500, tick: 5, dpt: 2500, dec: 0 },
    { ticker: 'CAC40', name: 'CAC 40 Index', cat: 'Index Futures', type: 'futures', dpp: 10, tick: 0.5, dpt: 5.00, dec: 1 },
    { ticker: 'STOXX50', name: 'Euro Stoxx 50', cat: 'Index Futures', type: 'futures', dpp: 10, tick: 1, dpt: 10.00, dec: 0 },
    { ticker: 'HSI', name: 'Hang Seng Index', cat: 'Index Futures', type: 'futures', dpp: 50, tick: 1, dpt: 50.00, dec: 0 },
    { ticker: 'ASX200', name: 'S&P/ASX 200', cat: 'Index Futures', type: 'futures', dpp: 25, tick: 1, dpt: 25.00, dec: 0 },
  ],
  metals: [
    { ticker: 'GC', name: 'Gold', cat: 'Metals', type: 'futures', dpp: 100, tick: 0.10, dpt: 10.00, dec: 1 },
    { ticker: 'MGC', name: 'Micro Gold', cat: 'Metals', type: 'futures', dpp: 10, tick: 0.10, dpt: 1.00, dec: 1 },
    { ticker: 'SI', name: 'Silver', cat: 'Metals', type: 'futures', dpp: 5000, tick: 0.005, dpt: 25.00, dec: 3 },
    { ticker: 'SIL', name: 'Micro Silver', cat: 'Metals', type: 'futures', dpp: 1000, tick: 0.005, dpt: 5.00, dec: 3 },
    { ticker: 'PL', name: 'Platinum', cat: 'Metals', type: 'futures', dpp: 50, tick: 0.10, dpt: 5.00, dec: 1 },
    { ticker: 'PA', name: 'Palladium', cat: 'Metals', type: 'futures', dpp: 100, tick: 0.10, dpt: 10.00, dec: 1 },
    { ticker: 'HG', name: 'Copper', cat: 'Metals', type: 'futures', dpp: 25000, tick: 0.0005, dpt: 12.50, dec: 4 },
  ],
  forex: [
    { ticker: 'EURUSD', name: 'EUR / USD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'GBPUSD', name: 'GBP / USD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'USDJPY', name: 'USD / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'AUDUSD', name: 'AUD / USD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'USDCAD', name: 'USD / CAD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'USDCHF', name: 'USD / CHF', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'NZDUSD', name: 'NZD / USD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'EURGBP', name: 'EUR / GBP', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'EURJPY', name: 'EUR / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'GBPJPY', name: 'GBP / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'AUDJPY', name: 'AUD / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'EURCHF', name: 'EUR / CHF', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'EURAUD', name: 'EUR / AUD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'EURCAD', name: 'EUR / CAD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'GBPAUD', name: 'GBP / AUD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'GBPCAD', name: 'GBP / CAD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'AUDCAD', name: 'AUD / CAD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'AUDNZD', name: 'AUD / NZD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'NZDJPY', name: 'NZD / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'CADJPY', name: 'CAD / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'CHFJPY', name: 'CHF / JPY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.01, pipVal: 10, dec: 3 },
    { ticker: 'USDMXN', name: 'USD / MXN', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 1, dec: 4 },
    { ticker: 'USDSGD', name: 'USD / SGD', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 10, dec: 4 },
    { ticker: 'USDZAR', name: 'USD / ZAR', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 0.5, dec: 4 },
    { ticker: 'USDTRY', name: 'USD / TRY', cat: 'Forex', type: 'forex', dpp: 1, tick: 0.0001, pipVal: 0.1, dec: 4 },
  ],
  crypto: [
    { ticker: 'BTC/USD', name: 'Bitcoin / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 1, dec: 0 },
    { ticker: 'ETH/USD', name: 'Ethereum / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'BTC/USDT', name: 'Bitcoin / USDT', cat: 'Crypto', type: 'spot', dpp: 1, tick: 1, dec: 0 },
    { ticker: 'ETH/USDT', name: 'Ethereum / USDT', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'SOL/USD', name: 'Solana / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'XRP/USD', name: 'Ripple / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.0001, dec: 4 },
    { ticker: 'ADA/USD', name: 'Cardano / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.0001, dec: 4 },
    { ticker: 'DOT/USD', name: 'Polkadot / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'DOGE/USD', name: 'Dogecoin / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.0001, dec: 4 },
    { ticker: 'LINK/USD', name: 'Chainlink / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'MATIC/USD', name: 'Polygon / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.0001, dec: 4 },
    { ticker: 'AVAX/USD', name: 'Avalanche / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'LTC/USD', name: 'Litecoin / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'BCH/USD', name: 'Bitcoin Cash / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'NEAR/USD', name: 'Near Protocol / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
    { ticker: 'UNI/USD', name: 'Uniswap / USD', cat: 'Crypto', type: 'spot', dpp: 1, tick: 0.01, dec: 2 },
  ],
};

export const PROFILE_COLORS = ['#0ea5e9', '#00d084', '#f59e0b', '#8b5cf6', '#f43f5e', '#14b8a6', '#fb923c', '#e879f9'];
